### ISSUE TITLE
Part 2: Switch back to the older pipe?

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/R-Fundamentals-Legacy#111]
Is usage of `|>` prevalent enough that we should instruct with it? I don't think enough people have updated R that this operator would be recognized. 

Could we switch back to %>%, but mention |> in passing so that the code works for people running older R?

**Comment by asteves** [comment]
We certainly can do so. The question is a bit about the nature of the workshop. If someone is coming to this having downloaded R for the first time, then they'll get the native pipe now. LMK if you think it's worth making the pipe updates.

**Comment by pssachdeva** [comment]
If you use a newer version of R, %>% will still work, right? And importing dplyr will automatically load that pipe into the namespace, correct? 

If both of these are true, I think we can switch back to the original pipe.

**Comment by asteves** [comment]
Yes. That's correct. The pull request #113 adds some form of that language to the workshop.
