### ISSUE TITLE
here package is worth mentioning 

### ISSUE THREAD

**Issue by jaeyk** [dlab-berkeley/R-Fundamentals-Legacy#14]
I think that the `here` package is worth mentioning even for the beginning users as `getwd()` + `setwd()` is not a good practice for reproducibility.

**Comment by Akesari12** [comment]
Added `here()` functionality in place of the `setwd()` stuff that was there, but wrapped `here()` in `setwd()`. This isn't the recommended way to use `here()` but I think trying to introduce relative file paths now would be tough.

**Comment by EastBayEv** [comment]
`setwd()` might still best to teach beginners and to really humanize the process re: navigating the file system and setting the working directory - a skill unto itself. Perhaps `here()` could be introduced in Part 3 and or 4 after participants have grasped the conceptual and technical elements for setting the working directory?

**Comment by Akesari12** [comment]
For now I've removed `here()` because it seems to return something slightly different on datahub v. a local machine. I think perhaps incorporating it into an intermediate workshop is the right move.
