### ISSUE TITLE
dplyr for sumarization 

### ISSUE THREAD

**Issue by jaeyk** [dlab-berkeley/R-Fundamentals-Legacy#15]
I don't know whether we should recommend the `psych` package or `dplyr` for summarization in PART 3-2. I understand that we need to teach enough base R but `psych` is not base R and its syntax is quite similar to `dplyr` and we introduce ggplot2 soon (PART 3-4) anyway.

**Comment by Akesari12** [comment]
It looks like we removed the `psych()` package now. Should we add some `dplyr` in or test it out and see how it works now?

**Comment by EastBayEv** [comment]
A little dplyr teaser would be nice, but maybe try it out this week and see how it flows?
