### ISSUE TITLE
replace iris dataset with penguine 

### ISSUE THREAD

**Issue by jaeyk** [dlab-berkeley/R-Fundamentals-Legacy#16]
Here's penguine dataset: https://github.com/allisonhorst/palmerpenguins

Also, the iris dataset originated from the Annals of Eugenics, in 1936, published by Ronald Fisher. It's time to reconsider its usage in the intro stat and data science courses.

**Comment by EastBayEv** [comment]
Thanks for these excellent issues raised, @jaeyk ! Updates coming soon.

**Comment by EastBayEv** [comment]
iris removed completely
