### ISSUE TITLE
Workshop Title

### ISSUE THREAD

**Issue by dlab-frontdesk** [dlab-berkeley/R-Fundamentals-Legacy#23]
Workshop title should be "R-Fundamentals:-Parts-1-4"

**Comment by asteves** [comment]
@pssachdeva @dlab-frontdesk Does it? If not, this issue should be closed.

**Comment by aculich** [comment]
Closing because repo should remain the same and anywhere else in plain text it should not be changed to the verbatim quote, as that would be incorrect.
