### ISSUE TITLE
Part 1: Error on accessing country column

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/R-Fundamentals-Legacy#25]
The current `Part1.R` script errors on lines 354 - 368 because of a typo in the country column (it doesn't capitalize "Country").

**Comment by Averysaurus** [comment]
Nice catch, thank you! Fixed just now.

**Comment by pssachdeva** [comment]
Thanks! Could you do it as a PR next time, just so that there's a record of the issue being matched to a PR/commit?

**Comment by Averysaurus** [comment]
Yes, apologies.
