### ISSUE TITLE
Part 2: Information about datasets

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/R-Fundamentals-Legacy#35]
We should include some information about the datasets, either in the README or in the script directly. For example, it's not totally clear what the `sleep_VIM` dataset is, and what the columns refer to. It would make the computations we perform more meaningful if students knew what the dataset consisted of, what the features were, and what units the columns were in.

**Comment by pattyf** [comment]
I completely agree but making metadata is a pain and it takes time to review. I think just renaming the columns to be self explanatory or using only the columns that are self explanatory would reduce cognitive noise in the fundamentals.
