### ISSUE TITLE
Part 3: removing statistical testing?

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/R-Fundamentals-Legacy#37]
This issue is for discussion. Is it worth keeping the statistical testing section after the introduction to visualization? It feels a bit odd because we're not explaining any of the details of the statistical testing - just demonstrating that it can be done. Furthermore, it feels only loosely connected to the previous part of the lesson.

I think it's totally fine to keep `geom_smooth` in there as a way to demonstrate that linear models can be fitted and plotted in one fell swoop. However, demonstrating the other functions may not be that effective since the lesson does not really go through the weeds.

**Comment by asteves** [comment]
On the one hand, it's definitely under covered. 

On the other hand, R is a statistical programming language first and foremost. It's a bit strange to go the entirety of fundamentals without mentioning the primary purpose of R. 

My view is that this ties into a more deep question about what we think the purpose of this workshop should be, and whether it should connect to other workshops more generally.
