### ISSUE TITLE
Part 4: Come up with a simpler example combining the core ideas

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/R-Fundamentals-Legacy#40]
Currently, the final example is rather involved: it requires writing a function for the birthday problem. This is somewhat advanced, and difficult to squeeze into what is already a full lesson. 

A simpler example could involve writing a naive function that checks whether a number is prime - this involves a function, a for loop, and an if statement, and simpler mathematical ideas.

**Comment by asteves** [comment]
It's been awhile since I taught R-Fundamentals, but might we want the example to be something a little bit more "fun" than calculating something like whether a number is prime?

**Comment by pssachdeva** [comment]
After reviewing this lesson, I think keeping the birthday problem is a good idea. Instead, we'll remove other components (e.g., the lock problem) so that the birthday problem can get more time.
