### ISSUE TITLE
DataHub Link error fix

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/R-Fundamentals-Legacy#70]
Was encountering issues with participants and how the DataHub link was formatted, (not loading into R-studio client). Formatted a new link and it seems to work on my end: 

https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdlab-berkeley%2FR-Fundamentals&urlpath=rstudio%2F&branch=main

**Comment by pssachdeva** [comment]
Great, can you update the README and create a pull request to make this change? Feel free to merge right away.

**Comment by asteves** [comment]
The link that @Averysaurus has in this comment is identical to the link in the README. 

```r
README <- "https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdlab-berkeley%2FR-Fundamentals&urlpath=rstudio%2F&branch=main"

newLink <- "https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdlab-berkeley%2FR-Fundamentals&urlpath=rstudio%2F&branch=main"

all.equal(README, newLink) # returns TRUE
```

Did you fix the README without closing this comment?

**Comment by Averysaurus** [comment]
Dang, you're right @asteves. Have not fixed the README myself. There's been a variety of results from people clicking this link. Errors I experienced myself and with a student was when the link loaded to a jupyter hub interface with workshop materials but not with R-studio up. Also tried this same same link today with our workshop team and they got errors and no access where it loaded for me just fine. 

Does the link work for you when you click on it?

**Comment by asteves** [comment]
Yes. That link works for me without issue.

**Comment by Averysaurus** [comment]
I tested this out with others and there's been errors on the first instance, (when someone clicks link the first time), but then spins up correctly the second time they click the link.

**Comment by asteves** [comment]
By this do you mean that if participants hit refresh the link worked, or that they had to physically click the link twice?
