### ISSUE TITLE
zero is not a negative number

### ISSUE THREAD

**Issue by mcami** [dlab-berkeley/R-Fundamentals-Legacy#75]
It was pointed out in Day 4 that 0 is not a negative number. Two of the example if else statements (lines 208-219 in Part4.R) produces results that say it is so ("0 is negative."). Code below. Could change line 216 and 226 to "x is less than 1" for example if we want to address this technicality, or add another else if statement for "x is equal to zero."

## Lastly, if we want to check for multiple conditions in a row, we can use else-if statements:
x <- 2
if (x > 3) {
  print("x is greater than 3.")
} else if (x > 0) {
  print("x is greater than 0.")
} else {
  print("x is negative.")
}

## Let's go ahead and put this if-else statement inside its own function, and run it inside a for-loop:
if_checker <- function(x) {
  if (x > 3) {
    print(paste0("x = ", x, ", is greater than 3."))
  } else if (x > 0) {
    print(paste0("x = ", x, ", is greater than 0."))
  } else {
    print(paste0("x = ", x, ", is negative."))
  }
}

**Comment by asteves** [comment]
I'll get this.
