### ISSUE TITLE
fix broken datahub link

### ISSUE THREAD

**Issue by aculich** [dlab-berkeley/R-Fundamentals-Legacy#77]
The [link to datahub](https://datahub.berkeley.edu/user/aculich/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdlab-berkeley%2FR-Fundamentals&urlpath=rstudio%2F&branch=main) is currently broken:
![image](https://user-images.githubusercontent.com/118965/151635883-f8651c4a-871a-4b9f-bed4-dd57ba82f0a9.png)

**Comment by pssachdeva** [comment]
It looks like it's trying to pull a `master` branch. We switched to a `main` branch a while ago. As far as I can tell, this is an edge case with nbgitpuller. A solution to this is to delete the repo on Datahub and try the link again.

**Comment by aculich** [comment]
Turns out the problem was related to already having a previous version of the R Fundamentals repo cloned on datahub, so deleting the old copy on datahub and relaunching works fine now.
