### ISSUE TITLE
Update install instructions for users with older OSes

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/R-Fundamentals-Legacy#79]
For example, Mac OS High Sierra users need to specifically install an older version of RStudio (1.3.1093). This is not apparent from the error message you get when attempting to install a newer version of RStudio.

**Comment by asteves** [comment]
@pssachdeva How far back do we want to go with these install instructions? FWIW I don't think High Sierra would be supported by any institutional IT in the UC system anymore.

**Comment by pssachdeva** [comment]
I think we just add caveats as we run into them, with a general tip on checking their OS if they're running into odd issues.

**Comment by asteves** [comment]
Sounds good. Other than High Sierra are there any others that we've run into?

**Comment by pssachdeva** [comment]
Not that I'm aware of.

**Comment by asteves** [comment]
Do you think it just makes more sense to tell students who have older versions to use Datahub?

**Comment by pssachdeva** [comment]
I think the specific case I ran into was someone who didn't have a Calnet ID, and so couldn't use DataHub.

We could just generalize this: "If you're running into odd issues, check your OS. Some older OSs require you to install a specific version of RStudio:..." with a link to [here](https://www.rstudio.com/products/rstudio/older-versions/) and recommendation to use the DataHub if possible.
