### ISSUE TITLE
ordering issue

### ISSUE THREAD

**Issue by e-belfer** [dlab-berkeley/R-Fundamentals-Legacy#82]
example on line 352 should refer to another column, or be moved elsewhere. This column is already sorted as it is entered.

**Comment by seanmperez** [comment]
Hi all, and thanks for addressing this @e-belfer!

I checked out your commit @asteves, and I think there may still be an issue due to not referencing row indexes.

If the goal is to show that we can sort rows by a column's values, we need a comma:
`df_sorted <- df[order(df$Area), ]`

**Comment by asteves** [comment]
@seanmperez Yep. You're right. Fixed.

**Comment by seanmperez** [comment]
@asteves so efficient!
