### ISSUE TITLE
Improvements for R Fundamentals Part2.Rmd

### ISSUE THREAD

**Issue by msamfair** [dlab-berkeley/R-Fundamentals-Legacy#90]
Thanks for the R-Fun update, I thought it flowed really well! When I was helping Marina with Part 2 yesterday, we just noticed a couple of things:

The working directory of the R Project file is somehow set to R-Fundamentals-main/lessons, rather than R-Fundamentals-main. Resetting the working directory inside a code chunk does not change it throughout the notebook, which caused some confusion. 

Also, on line 400, there are 2 commands on the same line that should be on two lines:
"sleep_select <- select(sleep_VIM, BodyWgt, BrainWgt) dim(sleep_select)"

Last thing is just a question - on line 414 where the pipe operator is introduced, there is a \ in "%\>%". Is that intentional so that the pipe symbol renders correctly once knitted?

Thanks and let me know if I can clarify anything!
Maya

**Comment by asteves** [comment]
I cannot replicate the R project working directory file problem. One possibility is that individuals are opening the .Rmd file before opening the Rproject file. 

Is this what happened?

**Comment by msamfair** [comment]
Oh good point, that is the source of the error. I'll mention that to Marina as well so we both know for next time, thanks Alex!
