### ISSUE TITLE
Part 2.rmd of R Fundamentals needs Xcode Command line tools

### ISSUE THREAD

**Issue by joseaveldanes** [dlab-berkeley/R-Fundamentals-Legacy#94]
Before getting to the end of part 2, some users had issues installing tidy verse to make use of the tibble package. Thus, people had issues following along at the end as a result of not being able to use Tibble.

**Comment by asteves** [comment]
@joseaveldanes This is a bit confusing because I don't see tibbles being used anywhere in R Fundamentals. Can you say more about what error message if any you saw?
