### ISSUE TITLE
File Path is broken by Rproj

### ISSUE THREAD

**Issue by asteves** [dlab-berkeley/R-Fundamentals-Legacy#96]
I'm not sure why no one reported this issue before, but as it stands the file paths are broken by the Rproj. This caused a huge problem in Part2 today.

**Comment by seanmperez** [comment]
It seems to work for the .R files, but not for the .Rmd files, and specifically in the .Rmd files it is the path autocomplete that is not identifying the correct root directory.

One fix here can be to use the .R files which do autocomplete paths to start at the same directory level that the .Rproj is in.

**Comment by asteves** [comment]
@seanmperez Perhaps the easiest path of least resistance is just to remove the .Rmd files. Thoughts?
